### ISSUE TITLE
Some elements can be an array or a hash, depending on the number of results

### ISSUE THREAD

**Issue by JasonBarnabe** [qbwc/qbwc#52]
You query for customers 100 at a time and you have 101 customers in QB. On the first `handle_response` call, `r['customer_ret']` will be an array of 100 customers. On the second call, it will be a hash of a single customer. This sucks to handle - it should always be an array.

**Comment by yos314** [comment]
I know this is a problem due to Washout.  It doesn't know whether we want an array or hash from the xml that its getting, so it just gives what it gives.  I currently am using: 
```r['item_service_ret'] = [r['item_service_ret']] unless Array === r['item_service_ret']```
in my own implementations, but I'm thinking that it probably could be worked into the qbxml gem?
I'll take a look at some point, but it won't be for a bit sadly.  Just wanted to bring up my one-liner solution that I put just before the `r['item_service_ret'].each` call.  (though i'm sure everyone already has these)

**Comment by sjagr** [comment]
+1 This is insane. I deal with external data values in Employees and am trying to parse it. When it's a single value, I get an array, and multiple values return a hash. This is greatly worsened for me because I have more single entry results in this scenario.

**Comment by JasonBarnabe** [comment]
This will happen in qbxml, so closing in favour of https://github.com/qbwc/qbxml/issues/17
