### ISSUE TITLE
Job request_index field type change

### ISSUE THREAD

**Issue by jhmoore** [qbwc/qbwc#85]
Hey all --

Love the gem, some really great work here.  

I have a question though about https://github.com/qbwc/qbwc/pull/80 . . . in https://github.com/bkroeker/qbwc/commit/94ad017d9889ac51ddde51c988a001af41f65703#diff-5c3a9fcea2be3f0c755232f1378467f0R8 it changes the datatype of the `request_index` field from integer to text, and adds an ActiveRecord `serialize :request_index, Hash` to the `Job` model.

Doesn't this break the gem for everybody who's already run the generator?  I bumped to the latest because I needed the changes in https://github.com/qbwc/qbwc/pull/72, and now everything is blowing up with either `ActiveRecord::SerializationTypeMismatch` or `Mysql2::Error` trying to serialize hashes in an integer field.

**Comment by JasonBarnabe** [comment]
There are a number of changes since the last release that would require you to regenerate the tables or make manual changes. I didn't think there were enough users of previous versions to make it worthwhile to write upgrade code. Anyone can write that up and I'll review it, but I don't have time to do it myself.

**Comment by jhmoore** [comment]
Ah ok thanks, good to know.  I guess I don't think upgrade code is necessarily required either, but putting up a blurb in the documentation would be nice for folks just getting into the project.

Is the next version going to be 1.0?

**Comment by JasonBarnabe** [comment]
Probably 0.2.
